// Generated by Copilot
// Sample extension test

import * as assert from 'assert';
import * as vscode from 'vscode';

suite('Extension Test Suite', () => {
  vscode.window.showInformationMessage('Start all tests.');

  test('Extension should be present', () => {
    assert.ok(vscode.extensions.getExtension('prismweave.prismweave-rag-assistant'));
  });

  test('Extension should activate', async () => {
    const extension = vscode.extensions.getExtension('prismweave.prismweave-rag-assistant');
    if (extension) {
      await extension.activate();
      assert.ok(extension.isActive);
    }
  });

  test('Commands should be registered', async () => {
    const commands = await vscode.commands.getCommands(true);
    
    const expectedCommands = [
      'prismweave.openChat',
      'prismweave.generateDocument',
      'prismweave.searchDocuments',
      'prismweave.refreshModels'
    ];

    for (const command of expectedCommands) {
      assert.ok(commands.includes(command), `Command ${command} should be registered`);
    }
  });
});
