#!/bin/bash
# Generated by Copilot
# Setup script for PrismWeave CLI tests

echo "========================================"
echo "  PrismWeave CLI Test Setup"
echo "========================================"
echo ""

# Check if Node.js is installed
if ! command -v node &> /dev/null; then
    echo "❌ Node.js is not installed. Please install Node.js 20.x or higher."
    exit 1
fi

# Check Node.js version
NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
if [ "$NODE_VERSION" -lt 20 ]; then
    echo "⚠️  Node.js version 20.x or higher is recommended. Current version: $(node -v)"
fi

echo "✓ Node.js version: $(node -v)"
echo ""

# Install dependencies
echo "📦 Installing dependencies..."
npm install

if [ $? -ne 0 ]; then
    echo "❌ Failed to install dependencies"
    exit 1
fi

echo "✓ Dependencies installed"
echo ""

# Build TypeScript
echo "🔨 Building TypeScript..."
npm run build

if [ $? -ne 0 ]; then
    echo "❌ Build failed"
    exit 1
fi

echo "✓ Build successful"
echo ""

# Run tests
echo "🧪 Running tests..."
npm test

if [ $? -ne 0 ]; then
    echo "❌ Some tests failed"
    exit 1
fi

echo ""
echo "✓ All tests passed!"
echo ""

# Generate coverage report
echo "📊 Generating coverage report..."
npm run test:coverage

echo ""
echo "========================================"
echo "  Setup Complete!"
echo "========================================"
echo ""
echo "Coverage report available at:"
echo "  cli/coverage/lcov-report/index.html"
echo ""
echo "Available commands:"
echo "  npm test              - Run all tests"
echo "  npm run test:watch    - Run tests in watch mode"
echo "  npm run test:coverage - Run tests with coverage"
echo ""
