// Generated by Copilot
// Configuration for bookmarklet generator

interface BookmarkletConfig {
  injectableBaseUrl: string;
  isDevelopment: boolean;
  version: string;
}

// Environment-based configuration
const getConfig = (): BookmarkletConfig => {
  const isDev = process.env.NODE_ENV === 'development';

  // Default to GitHub Pages for production, localhost for development
  const baseUrl = isDev
    ? 'http://localhost:3000/injectable'
    : 'https://davidhayesbc.github.io/prismweave/injectable';

  return {
    injectableBaseUrl: process.env.PRISMWEAVE_INJECTABLE_URL || baseUrl,
    isDevelopment: isDev,
    version: process.env.npm_package_version || '1.0.0',
  };
};

export const config = getConfig();
