// Generated by Copilot
// Shared interfaces for PrismWeave provider abstraction

export * from './notification-provider.js';
export * from './storage-provider.js';
export * from './tab-provider.js';

// Common dependency injection interface
export interface IPrismWeaveDependencies {
  storageProvider: import('./storage-provider.js').IStorageProvider;
  notificationProvider: import('./notification-provider.js').INotificationProvider;
  tabProvider: import('./tab-provider.js').ITabProvider;
}
